FROM node:20-bullseye-slim

# Install Tor and clean up cache to keep the image small
RUN apt-get update && apt-get install -y tor && rm -rf /var/lib/apt/lists/*

# Set up your Node environment
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Run Tor in the background (&), wait 3 seconds for circuits to build, then start the worker
CMD tor & sleep 3 && node spiderWorker.js