# Use Debian-based Node image
FROM node:20-bullseye

# Install Tor
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs
# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy worker code
COPY spiderWorker.js .

# Start Tor in the background, wait 5 seconds for circuits to build, then start the Node worker
CMD service tor start && sleep 5 && node spiderWorker.js